# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.loglikRE <- function(CovRE, REs, qvec, ni) {
    .Call('_wglmm_loglikRE', PACKAGE = 'wglmm', CovRE, REs, qvec, ni)
}

.loglikCond <- function(REs, phi, family, X, y, Z, weights, scale) {
    .Call('_wglmm_loglikCond', PACKAGE = 'wglmm', REs, phi, family, X, y, Z, weights, scale)
}

.loglikTot <- function(REs, phi, family, X, y, Z, CovRE, weights, qvec, ni, scale) {
    .Call('_wglmm_loglikTot', PACKAGE = 'wglmm', REs, phi, family, X, y, Z, CovRE, weights, qvec, ni, scale)
}

.loglikCondImp <- function(REs, phi, family, X, y, Z, weights, weightsImp, scale) {
    .Call('_wglmm_loglikCondImp', PACKAGE = 'wglmm', REs, phi, family, X, y, Z, weights, weightsImp, scale)
}

.loglikREImp <- function(CovRE, REs, qvec, ni, weightsImp) {
    .Call('_wglmm_loglikREImp', PACKAGE = 'wglmm', CovRE, REs, qvec, ni, weightsImp)
}

.loglikTotImp <- function(REs, phi, family, X, y, Z, CovRE, weights, qvec, ni, weightsImp, scale) {
    .Call('_wglmm_loglikTotImp', PACKAGE = 'wglmm', REs, phi, family, X, y, Z, CovRE, weights, qvec, ni, weightsImp, scale)
}

.GradientAll <- function(REs, phi, family, X, y, Z, CovRE, weights, qvec, ni, scale) {
    .Call('_wglmm_GradientAll', PACKAGE = 'wglmm', REs, phi, family, X, y, Z, CovRE, weights, qvec, ni, scale)
}

.GradientBetaImp <- function(REs, phi, family, X, y, Z, weights, weightsImp, scale) {
    .Call('_wglmm_GradientBetaImp', PACKAGE = 'wglmm', REs, phi, family, X, y, Z, weights, weightsImp, scale)
}

.HessianBetaImp <- function(REs, phi, family, X, y, Z, weights, weightsImp, scale) {
    .Call('_wglmm_HessianBetaImp', PACKAGE = 'wglmm', REs, phi, family, X, y, Z, weights, weightsImp, scale)
}

.NewCoefImp <- function(REs, phi, family, X, y, Z, weights, weightsImp, tol, MaxIt, scale) {
    .Call('_wglmm_NewCoefImp', PACKAGE = 'wglmm', REs, phi, family, X, y, Z, weights, weightsImp, tol, MaxIt, scale)
}

.NewCovREImp <- function(REs, qvec, ni, weightsImp) {
    .Call('_wglmm_NewCovREImp', PACKAGE = 'wglmm', REs, qvec, ni, weightsImp)
}

.ImportanceSampling <- function(MI, modus, Chol, phi, family, X, y, Z, CovRE, weights, qvec, ni, scale) {
    .Call('_wglmm_ImportanceSampling', PACKAGE = 'wglmm', MI, modus, Chol, phi, family, X, y, Z, CovRE, weights, qvec, ni, scale)
}

.GenModusNeu <- function(REs, phi, family, X, y, Z, CovRE, weights, qvec, ni, tol, MaxIt, Chol, scale) {
    .Call('_wglmm_GenModusNeu', PACKAGE = 'wglmm', REs, phi, family, X, y, Z, CovRE, weights, qvec, ni, tol, MaxIt, Chol, scale)
}

.wlmm_transform_cpp <- function(phi, transform, X, y, Z, CovRE, weights, qvec, ni, scale, lambda, MI, iter1, iter2, tol1, tol2, trace, nDecrease) {
    .Call('_wglmm_wlmm_transform_cpp', PACKAGE = 'wglmm', phi, transform, X, y, Z, CovRE, weights, qvec, ni, scale, lambda, MI, iter1, iter2, tol1, tol2, trace, nDecrease)
}

